spring:

  server:
    port: 8081

  datasource:
    platform: firebird
    url: jdbc:firebirdsql://IP:PORT//opt/interbase/data/db.fdb
    username: user
    password: pass
    driverClassName: org.firebirdsql.jdbc.FBDriver
